version: '3.4'

services:
  moment:
    image: moment
    build:
      context: node_modules/moment
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
